import moment from 'moment'

export const initialData = {
	timeRange: { from: '08:00', to: '20:00' },
	timeFrameDuration: 30,
	days:[
		{
			_id: '0',
			label: moment().format('dddd MMM Do'),
			timeFrames: [
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
			]
		},
		{
			_id: '1',
			label: moment().add(1, 'day').format('dddd MMM Do'),
			timeFrames: [
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
			]
		},
		{
			_id: '2',
			label: moment().add(2, 'day').format('dddd MMM Do'),
			timeFrames: [
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
			]
		},
		{
			_id: '3',
			label: moment().add(3, 'day').format('dddd MMM Do'),
			timeFrames: [
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
			]
		},
		{
			_id: '4',
			label: moment().add(4, 'day').format('dddd MMM Do'),
			timeFrames: [
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
			]
		},
		{
			_id: '5',
			label: moment().add(5, 'day').format('dddd MMM Do'),
			timeFrames: [
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: ['', '', '', '', '', '', '', ''] },
				{ reservations: [] },
			]
		},
		{
			_id: '6',
			label: moment().add(6, 'day').format('dddd MMM Do'),
			timeFrames: [
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [ 'user_1', 'user_2' ] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
				{ reservations: [] },
			]
		}
	]
}